FROM debian

# Actualiza los paquetes e instala strace, netcat-traditional y procps para obtener ps
RUN apt update && apt install -y strace netcat-traditional procps

# CMD se maneja en el docker-compose
